Close if condition in the configmap.yaml (#15524)
Currently syntaxis in the deploy/kubernetes/helm/che/templates/configmap.yaml file is broken. It causes an error when trying to execute helm upgrade command:

$ helm upgrade che --set global.useGitSelfSignedCerts=true --set global.ingressDomain=$(minikube ip).nip.io .
UPGRADE FAILED
Error: parse error in "che/templates/configmap.yaml": template: che/templates/configmap.yaml:136: unexpected EOF
Error: UPGRADE FAILED: parse error in "che/templates/configmap.yaml": template: che/templates/configmap.yaml:136: unexpected EOF
see: https://www.eclipse.org/che/docs/che-7/advanced-configuration-options/#configuring-support-for-self-signed-git-repositories-on-kubernetes

Add missing close statement to fix the error.